Feature/#3 get user info
DVitushkin/Vitushkin_Advanced_REST_Server pull request #4
Opened 2024-01-17 14:05 UTC by DVitushkin

Add endpoints to:
* get all users info
* get user info 
* get user info by id

2024-01-17 15:35 UTC, MVlasovD requested changes

2024-01-17 15:35 UTC, MVlasovD commented on src/main/java/com/dunice/Vitushkin_Advanced_REST_Server/repository/UserRepository.java
> +    Optional<User> findById(Long id);
на все методы в репозитории нужно написать запросы через аннотацию query

2024-01-17 15:35 UTC, MVlasovD commented on src/main/java/com/dunice/Vitushkin_Advanced_REST_Server/views/PublicUserView.java
> +@Builder
пробывал аннотация ломбока Accessors?

2024-01-18 06:14 UTC, DVitushkin commented on src/main/java/com/dunice/Vitushkin_Advanced_REST_Server/views/PublicUserView.java
> +@Builder
в текущей версии только в LogEntity, для построения записи в лог в LoggerInterceptor классе

2024-01-18 08:05 UTC, MVlasovD approved these changes

2024-01-18 08:06 UTC, merged